package com.network.task.util;

import java.util.HashMap;

public class CountryMappingUtil {
	
	public static HashMap<String, String>  countryMap = new HashMap<String, String>();
	
	static{
			countryMap.put("CHN","CN");
			countryMap.put("CHN","CN");
			countryMap.put("JPN","JP");
			countryMap.put("PRK","KP");
			countryMap.put("KOR","KR");
			countryMap.put("MNG","MN");
			countryMap.put("HKG","HK");
			countryMap.put("MAC","MO");
			countryMap.put("TWN","TW");
			countryMap.put("VNM","VN");
			countryMap.put("THA","TH");
			countryMap.put("MYS","MY");
			countryMap.put("IDN","ID");
			countryMap.put("PHL","PH");
			countryMap.put("SGP","SG");
			countryMap.put("LAO","LA");
			countryMap.put("BRN","BN");
			countryMap.put("KHM","KH");
			countryMap.put("MMR","MM");
			countryMap.put("TLS","TL");
			countryMap.put("BGD","BD");
			countryMap.put("BTN","BT");
			countryMap.put("IND","IN");
			countryMap.put("MDV","MV");
			countryMap.put("NPL","NP");
			countryMap.put("LKA","LK");
			countryMap.put("PAK","PK");
			countryMap.put("CRI","CR");
			countryMap.put("USA","US");
			countryMap.put("CAN","CA");
			countryMap.put("MEX","MX");
			countryMap.put("HND","HN");
			countryMap.put("GTM","GT");
			countryMap.put("CUB","CU");
			countryMap.put("BHS","BS");
			countryMap.put("PAN","PA");
			countryMap.put("JAM","JM");
			countryMap.put("HTI","HT");
			countryMap.put("BLZ","BZ");
			countryMap.put("BRB","BB");
			countryMap.put("GRD","GD");
			countryMap.put("NIC","NI");
			countryMap.put("DMA","DM");
			countryMap.put("DOM","DO");
			countryMap.put("TTO","TT");
			countryMap.put("PRI","PR");
			countryMap.put("ARG","AR");
			countryMap.put("BRA","BR");
			countryMap.put("BOL","BO");
			countryMap.put("CHL","CL");
			countryMap.put("COL","CO");
			countryMap.put("ECU","EC");
			countryMap.put("GUY","GY");
			countryMap.put("PRY","PY");
			countryMap.put("PER","PE");
			countryMap.put("SUR","SR");
			countryMap.put("URY","UY");
			countryMap.put("VEN","VE");
			countryMap.put("EGY","EG");
			countryMap.put("SDN","SD");
			countryMap.put("LBY","LY");
			countryMap.put("TUN","TN");
			countryMap.put("DZA","DZ");
			countryMap.put("MAR","MA");
			countryMap.put("MRT","MR");
			countryMap.put("SEN","SN");
			countryMap.put("GMB","GM");
			countryMap.put("MLI","ML");
			countryMap.put("BFA","BF");
			countryMap.put("GIN","GN");
			countryMap.put("GNB","GW");
			countryMap.put("CPV","CV");
			countryMap.put("SLE","SL");
			countryMap.put("LBR","LR");
			countryMap.put("CIV","CI");
			countryMap.put("GHA","GH");
			countryMap.put("TGO","TG");
			countryMap.put("BEN","BJ");
			countryMap.put("NER","NE");
			countryMap.put("NGA","NG");
			countryMap.put("ETH","ET");
			countryMap.put("KEN","KE");
			countryMap.put("TZA","TZ");
			countryMap.put("UGA","UG");
			countryMap.put("RWA","RW");
			countryMap.put("SYC","SC");
			countryMap.put("DJI","DJ");
			countryMap.put("SOM","SO");
			countryMap.put("ERI","ER");
			countryMap.put("TCD","TD");
			countryMap.put("CAF","CF");
			countryMap.put("CMR","CM");
			countryMap.put("GNQ","GQ");
			countryMap.put("GAB","GA");
			countryMap.put("COG","CG");
			countryMap.put("COD","CD");
			countryMap.put("ZMB","ZM");
			countryMap.put("AGO","AO");
			countryMap.put("ZWE","ZW");
			countryMap.put("ZAF","ZA");
			countryMap.put("MUS","MU");
			countryMap.put("NAM","NA");
			countryMap.put("MOZ","MZ");
			countryMap.put("MWI","MW");
			countryMap.put("SWZ","SZ");
			countryMap.put("MDG","MG");
			countryMap.put("COM","KM");
			countryMap.put("LSO","LS");
			countryMap.put("SWE","SE");
			countryMap.put("FIN","FI");
			countryMap.put("NOR","NO");
			countryMap.put("DNK","DK");
			countryMap.put("ISL","IS");
			countryMap.put("GBR","UK");
			countryMap.put("IRL","IE");
			countryMap.put("NLD","NL");
			countryMap.put("BEL","BE");
			countryMap.put("LUX","LU");
			countryMap.put("FRA","FR");
			countryMap.put("MCO","MC");
			countryMap.put("RUS","RU");
			countryMap.put("EST","EE");
			countryMap.put("LVA","LV");
			countryMap.put("LTU","LT");
			countryMap.put("UKR","UA");
			countryMap.put("BLR","BY");
			countryMap.put("MDA","MD");
			countryMap.put("POL","PL");
			countryMap.put("DEU","DE");
			countryMap.put("CHE","CH");
			countryMap.put("AUT","AT");
			countryMap.put("HUN","HU");
			countryMap.put("CZE","CZ");
			countryMap.put("SVK","SK");
			countryMap.put("LIE","LI");
			countryMap.put("ESP","ES");
			countryMap.put("PRT","PT");
			countryMap.put("ITA","IT");
			countryMap.put("ROU","RO");
			countryMap.put("BGR","BG");
			countryMap.put("SRB","RS");
			countryMap.put("HRV","HR");
			countryMap.put("SVN","SI");
			countryMap.put("GRC","GR");
			countryMap.put("ALB","AL");
			countryMap.put("MNE","ME");
			countryMap.put("MKD","MK");
			countryMap.put("SMR","SM");
			countryMap.put("MLT","MT");
			countryMap.put("AND","AD");
			countryMap.put("SYR","SY");
			countryMap.put("IRQ","IQ");
			countryMap.put("ISR","IL");
			countryMap.put("ARE","AE");
			countryMap.put("TUR","TR");
			countryMap.put("IRN","IR");
			countryMap.put("GBR","GB");
			countryMap.put("SAU","SA");
			countryMap.put("QAT","QA");
			countryMap.put("AUS","AU");
			countryMap.put("BHR","BH");
	    };
	
	/**
	 * 通过 country3ch 获取 country
	 * 
	 * @param country3ch
	 * @return
	 */
	public static String getCountryByCountry3ch(String country3ch){
		
		return countryMap.get(country3ch);
	}

}
